### ISSUE TITLE
デフォルトの表示

### ISSUE THREAD

**Issue by wata909** [ai-pest/ai_pumpkin#1]
@nss-ysasaki  
 デフォルト（起動時）の表示について，以下のように変更可能でしょうか

- 背景地図は，OSMのオフライン版とする
- 表示位置を北海道の低ズームレベルにする

**Comment by ghost** [comment]
PR #2 を出しました。ご確認ください。

**Comment by wata909** [comment]
ありがとうございます。マージしましたのでcloseします。
